### ISSUE TITLE
Identify parts to be redesigned

### ISSUE THREAD

**Issue by Maciejgrybko** [Juliankautsch/F19#10]
- Anti-roll bar
- Exhaust
- Fuel tank
- Steering wheel
What else?

**Comment by Juliankautsch** [comment]
Front suspension
Plenum
Nosecone
Undertray
Rockers (front and rear)
Rear wing
Front wing 
Steering geometry
Steering column
Seat
Electrical system
Chain guard
Maybe:
Firewall
Expansion chamber
Cooling system
Shifting mechanism

**Comment by Juliankautsch** [comment]
Rear absorber system (done as in LFRT18 but needs to be designed and drawn)
