### ISSUE TITLE
Copy wheels and attach to uprights

### ISSUE THREAD

**Issue by Maciejgrybko** [Juliankautsch/F19#124]
- copy wheels from LFRT18
- name them F19_WT_Wheel
- attach to uprights in F19_SU_FrontUpright and F19_SU_RearUpright assemblies

**Comment by VoramesVilleneuve** [comment]
Cant find these uprights in the f19 folder. Should i copy the LFRT18 latest version and rename them?

**Comment by VoramesVilleneuve** [comment]
should i also attach hubs,disc brake,spindle and steering arm to them as well? i'll get it done later today.

**Comment by VoramesVilleneuve** [comment]
just finished the assembly of the front upright and wheel. this includes some additional parts, steering arm, upright front bracket, disc brake, etc. I also renamed and put these additional parts in to system files they belong to. going to work on the rear now

**Comment by VoramesVilleneuve** [comment]
Did the same thing on the rear. all assembly are now in N drive F19 file
