### ISSUE TITLE
Copy uprights

### ISSUE THREAD

**Issue by Maciejgrybko** [Juliankautsch/F19#32]
- create 2 folders within Suspension folder and in each folder 1 assembly of the same name: F19_SU_FrontSuspension and F19_SU_RearSuspension
- note: these assemblies represent only 1 side of suspension system (either left or right)
- copy uprights (just 1 to each assembly) from LFRT18 and name them F19_SU_FrontUpright and F19_SU_RearUpright

**Comment by VoramesVilleneuve** [comment]
I have copied the uprights in to the folders. think these are the correct ones.
